# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

**Please note again that we are using 0 to represent heads, and 1 to represent tails.**

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [9]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.249444

In [12]:
tests = np.random.randint(2, size=(int(1e6), 2))
tests

array([[0, 1],
       [0, 0],
       [0, 1],
       ..., 
       [1, 0],
       [0, 1],
       [1, 0]])

In [17]:
test_sums = tests.sum(axis=1)
test_sums

array([1, 0, 1, ..., 1, 1, 1])

In [18]:
(test_sums == 0).mean()

0.250585

### 2. Three fair coin flips produce exactly one head

In [33]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.37578899999999998

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [22]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()
tests = np.random.choice([0,1], size=(int(1e6), 3), p=[0.6,0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums==0).mean()

0.21590000000000001

### 4. A die rolls an even number

In [28]:
tests = np.random.choice(np.arange(1, 7), size=(int(1e6)))
tests

array([3, 3, 5, ..., 4, 2, 1])

In [29]:
(tests % 2 == 0).mean()

0.50014700000000001

In [30]:
# simulate 1 million tests of one die roll
tests = np.random.choice(np.arange(1, 7), size=(int(1e6)))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.50014000000000003

### 5. Two dice roll a double

In [31]:
# simulate the first million die rolls
first = np.random.choice(np.arange(1,7), size=(int(1e6)))

# simulate the second million die rolls
second = np.random.choice(np.arange(1,7), size=(int(1e6)))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.16688600000000001